### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#138]
[following this example](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx)

If someone has a local clone, then can update their locals like this:
```
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Comment by BrandonDyer64** [comment]
But why? Why create friction for no apparent benefit?

**Comment by markusweimer** [comment]
> But why? Why create friction for no apparent benefit?

The benefit is the reduction of language in tech that is uncomfortable from a race relations perspective in the US.

At the same time, it is just good naming. Finding good names in software is always hard. And `master` is particularly useless choice of name: There is nothing the `master` branch particularly excels at. But it is where the main part of the development happens. Hence, `main` is much more clear, concise and appropriate name.

**Comment by ksaur** [comment]
Thanks for your interest in our project!

If renaming something is the most friction I experience in a day, then I am having a pretty good day.

**Comment by BrandonDyer64** [comment]
I still see a few issues with this though.

> The benefit is the reduction of language in tech that is uncomfortable from a race relations perspective in the US.

Is this actually an issue? Does anyone attribute the word "master" with racial issues? What about "master copy" or "master's degree" or "master tape"?

Doesn't renaming it also create inconsistencies with other projects on GitHub? "master" has been the de facto name for the bottom-most branch for more than a decade. Won't this become confusing when people expect the branch to be named "master"?

I promise I'm not trying be argumentative, or imply that I don't understand how much racial issues are a problem in the US, but this change doesn't really seem to do anything to help.

Wouldn't a better change be to put links and information about racial inequality and how people can help into the Readme?

**Comment by markusweimer** [comment]
> Is this actually an issue? Does anyone attribute the word "master" with racial issues?

As a somewhat recent immigrant to the US, I don't feel qualified to answer this. But from reading and conversations, I conclude: Yes, very much so. And clearly worth the small hassle.

> Doesn't renaming it also create inconsistencies with other projects on GitHub?

No. GitHub itself is changing the default, and there are efforts underway to do the same for `git init`. `master` will soon be a mark of poorly maintained projects, which Hummingbird clearly is not.

> Wouldn't a better change be to put links and information about racial inequality and how people can help into the Readme?

That is a step into the territory of social activism. OSS is inherently political. But I am not sure Hummingbird as a project is here to address societal issues. Then again, I am not a maintainer of the project and might be wrong here.

To me, `master` vs. `main` is much simpler: `master` is a bad name, because it does not convey the role of the branch accurately. It also is a word that is problematic to a large group of people. `main` addresses both these issues with limited effort.

**Comment by ksaur** [comment]
> Doesn't renaming it also create inconsistencies with other projects on GitHub? 

https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by curino** [comment]
Thanks folks for thinking about this! I think it is very low cost and totally worth it even if it is just symbolic. I am also in favor of care in naming and examples within the code and documentation (e.g., avoiding racist/ableist/patriarchal/anti-lgbt/etc.. terminology).

**Comment by ksaur** [comment]
done
