### ISSUE TITLE
pip install hummingbird-ml does not work on windows

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#166]
To reproduce, just run `pip install hummingbird-ml`. I get ` ERROR: Could not find a version that satisfies the requirement torch>=1.4.0 (from hummingbird-ml==0.0.3) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.4.0 (from hummingbird-ml==0.0.3)`. 

Apparently the proper branch in `setup.py` is not picked up.

**Comment by ksaur** [comment]
Interesting.  Does this install some other way rather than calling the setup file ([with the exact package specified](https://github.com/microsoft/hummingbird/blob/master/setup.py#L28))?  

It's a bit frustrating because it works in the ci/cd.... (Ex:[ this run](https://github.com/microsoft/hummingbird/runs/797123213#step:4:17)).  I wonder what is different because the installer (at least appears) is called the same way.

**Comment by ksaur** [comment]
Just curious....Does this also happen when you do `pip install hummingbird-ml[extra,tests]` ?

**Comment by interesaaat** [comment]
I dig a bit into this. 
- `pip install hummingbird-ml[extra,tests]` does not work either.
- from pip it is pulling the binaries, and binaries uses the requirements for linux\mac (because we built them from a linux machine). I thought that we can try to push the binaries also for win, but
- if you `pip install hummingbird-ml --no-binaries` you get something like "cannot install torch from torch @ http:// ... because it is not on pip". 
- pip install -e . works because you are not using `pypi`.

I don't think there is any solution for windows at the moment beyond manually installing torch (or installing from the repo directly)

**Comment by interesaaat** [comment]
One possibility is to switch to conda. Pytorch for windows is available there.

**Comment by ksaur** [comment]
Ugh, ok, I was afraid it was pulling from the binaries; makes sense of course!
Other than hosting a separate mirror of torch 1.5 on pypi that we point too, I don't see a great solution for now other than switching to conda (as you just typed as well haah)

**Comment by amueller** [comment]
I might be able to help but I'm not sure if I understand the issue.
There are no binaries in hummingbird-ml, right?

ps: I was auto-subscribed to hummingbird but I unsubscribed because my inbox is too full. Feel free to ping me where I can be helpful though.

**Comment by ksaur** [comment]
Ah, bad choice of words, what I meant was: When someone pulls from pypi (ex: `pip install hummingbird-ml`) it seems to be just pulling the prebuilt hummingbird .whl rather than calling into our cleverly crafted `setup.py` which checks to see if the OS is windows and then installs pytorch via url.  (see links above.)   If you have ideas that would be awesome!
