### ISSUE TITLE
Faster compilation?

### ISSUE THREAD

**Issue by zhanjiezhu** [microsoft/hummingbird#181]
In the notebooks, the prediction time of sklearn is compared with the prediction time of hummingbird converted model (either in cpu or gpu). However, the time for compiling the sklearn model into hummingbird model is not taken into account.

This is what I get when running the blog_example and also time the "convert" function:
sklearn prediction: 48.3 ms ± 607 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
time for compiling sklearn into hummingbird: 221 ms ± 3.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
hummingbird cpu prediction: 14.4 ms ± 92.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

So the time for compilation become bottleneck, I guess solution would be to save the compiled model and use it directly for later inference. But is it possible to improve the compilation speed as well? I guess it's slow because it need to traverse the trees and get the nn parameters, and I also observed this when adding the support for Isolation Forest because I need to again traverse the trees and get the node depths.

**Comment by ksaur** [comment]
Hi @zhanjiezhu,

Yes, depending on the model, conversion can take a few hundred milliseconds, especially depending on the shape of the tree.  The usual mode of operation is "convert once, predict many", in that model conversion is not typically in the "critical path" for running fast predictions.

Because of this normal use-case, lightening-fast model conversion has not been a top priority and has not a "bottleneck" because conversion is only done once.  That said, we're always looking for ways to make all aspects of Hummingbird faster!

And if you have a different production use-case where model conversion is the bottleneck, we'd love to hear more details!

**Comment by zhanjiezhu** [comment]
Thanks @ksaur, closing it now.
