### ISSUE TITLE
Installing on windows installs torch-1.5.1+cpu?

### ISSUE THREAD

**Issue by sword134** [microsoft/hummingbird#220]
Hello,
I am running the following command in my conda terminal `pip install hummingbird-ml -f https://download.pytorch.org/whl/torch_stable.html` the result is that it installs torch-1.5.1+cpu therefore I am not able to use cuda when converting my model. If I manually install pytorch then hummingbird wont work since its missing torch-1.5.1+cpu but at least `print(torch.cuda.is_available())` will return true.

How do I fix this?

**Comment by interesaaat** [comment]
Yes by default HB comes with the cpu version of pytorch. We decided so because it is impossible to know which GPU version to install.
What you did is correct. You need to uninstall the cpu version and install the one with the proper cuda version. You will get a warning, but Hummingbird will still work. We will have to check on how to fix this because I agree, it is a weird solution. One possibility we thought about is to have no dependencies on pytorch so that users are forced to install the proper one manually. But in that case pip install will not work out of the box. Any suggestion?

**Comment by sword134** [comment]
Ok i am uninstalling everything (hummingbird and pytorch) and going to run the following `command conda install pytorch torchvision cudatoolkit=10.1 -c pytorch` followed by a `pip install hummingbird-ml` do you think it will work? Its currently downloading and extracting (pytorch takes a long time). If I run my code with model.to("cuda") will hummingbird-ml then work or will it complain about not having 1.5.1+cpu installed?

I will edit this comment once I try it out

**Comment by sword134** [comment]
@interesaaat Well I did conda install of the latest pytorch version, however when trying to install hummingbird-ml via pip I get the following error: 
```
ERROR: Could not find a version that satisfies the requirement torch==1.5.1+cpu
(from hummingbird-ml) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.1+cpu (from hummingbird-ml)
```
Installing hummingbird-ml==0.0.2 works though, however that version doesn't support logistic regression which is what I need hummingbird-ml for :/

**Comment by sword134** [comment]
@interesaaat Alright I found the solution. Build hummingbird-ml from the github repo by cloning it and then running `python setup.py install`

**Comment by ksaur** [comment]
Thanks for reporting what worked! Making the installer work across all platforms and possible configurations has been a challenge, thanks for bearing with us!
