### ISSUE TITLE
Isolation Forest results do not match in sklearn 0.21.3

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#275]
To reproduce: run isolation forest tests with `scikit-learn==0.21.3`

**Comment by ksaur** [comment]
Is there some way around rolling back `sklearn` to `0.21.3` in #274 ?

**Comment by zhanjiezhu** [comment]
I can reproduce this, it only throws errors on "predict" but fine for "decision_function" and "score_samples", so must be problem with the offset in "predict". It's due to in 0.21.3, the "behaviour" defaults to "old", which cause the "predict" rely on the value "_threshold_" which is already removed in 0.22 onwards. To make it also work for 0.21.3, I think we can try to parse the _threshold_ if exist, otherwise set 0.

**Comment by interesaaat** [comment]
Thanks @zhanjiezhu for looking into this. The fix should be easy.

**Comment by zhanjiezhu** [comment]
Hi @interesaaat, are you already fixing it? if not, I'm happy to help :)

**Comment by ksaur** [comment]
We would love to have your help, thanks! :)
