### ISSUE TITLE
Verify notebook-based pip install

### ISSUE THREAD

**Issue by ksaur** [microsoft/hummingbird#298]
I'm not familiar with the `collab` notebook environment.  I'm looking at all of our notebooks, and I see that we have text like `pip install hummingbird_ml[extra]` at the top of all of them. This was added by a `collab` user (ex: #150).

I would expect this to be `pip install hummingbird-ml[extra]` with a dash, not underscore...but before I change it back maybe there is a notebook environment difference that I am not aware of!

Could someone who is familiar with `collab` test our pip install import on both collab and jupyter in our notebook examples? And change it if necessary or close this issue if not?

Thanks!!

**Comment by saadhaxxan** [comment]
Actually, the inline pip statement in jupyter or colab is used to install the library if not installed before its just like running a pip install in cmd. Pip uses whl file or a separate pypa uploaded library to install the dependencies and library. In your case, I think its a whl file which is in hummingbird_ml[extra] format for it pip requires an underscore to install giving a dash will give an error because the file names do not contain dash rather it contains an underscore.

![screenshot](https://user-images.githubusercontent.com/42111836/95671114-88109280-0bac-11eb-8169-d86c34ccc6c5.png)

**Comment by saadhaxxan** [comment]
After verification, I have seen that the notebook statement with underscore also works fine and a statement with dash also does the same so nothing to worry about. Now it's all up to which you want an underscore or a dash 👍

**Comment by ksaur** [comment]
Thank you for verifying @saadhaxxan!
