### ISSUE TITLE
How to persist Hummingbird Models?

### ISSUE THREAD

**Issue by setuc** [microsoft/hummingbird#321]
What is the recommended way to persist in Hummingbird models? Is pickle the recommended way?

**Comment by ksaur** [comment]
Hi @setuc ! Hummingbird does not change the way the models are persisted, so no need to do anything different/special.

For example, if you convert a scikit-learn model to PyTorch, you would simply persist the converted model the same as any other PyTorch model. (ex: [PyTorch docs](https://pytorch.org/tutorials/beginner/saving_loading_models.html))

Hopefully this makes sense! If you have further/specific doubts, please post them!

**Comment by interesaaat** [comment]
Let me elaborate a bit on this. I think this is actually a good question we somehow overlooked. As Karla mentioned, at the moment you can persist each model using the "native model way". For instance if you convert to pytorch you can do 
`torch.save(your_hb_converted_model.model, path)`. 

There are two problems with this:
- Users will have to implement save\load code specific for each target model type (e.g., in onnx you save differently than torch because you need to call `onnx.save(...)`)
- We will lose the Sklearn container when models are loaded (unless users explicitly instantiate a container and wrap the loaded model).

Bottomline: I think we will need to provide save\load primitives in HB such that we can avoid the above drawbacks.
