### ISSUE TITLE
Batch inference API for backends that require fixed batch size (TVM)

### ISSUE THREAD

**Issue by masahi** [microsoft/hummingbird#368]
TVM backend requires a fixed batch size specified at convert time. Currently, hummingbird uses [_run_batch_inference](https://github.com/microsoft/hummingbird/blob/main/hummingbird/ml/_container.py#L89) function to run prediction on test data whose batch size is bigger than the batch size TVM is compiled for.

`hb_model.predict(test_data)` is supposed to work the same way as sklearn does, and that is taken care of by `_run_batch_inference` above. But this has two problems for TVM backend, in terms of CPU overhead spent outside of TVM:

* It requires allocating a large array to hold each fixed-size batch prediction (related PR https://github.comhttps://github.com/microsoft/hummingbird/pull/366/microsoft/hummingbird/pull/366)
* And copying each batch prediction to the result array

For the first item, during the work of https://github.com/microsoft/hummingbird/pull/366 I found that pre-allocating a prediction array inside `_run_batch_inference` is not straightforward, since it is used by all prediction tasks. For classification and regression it is no problem, but for transform it doesn't seem to work. So I want to close that PR and instead deal with the CPU overhead problem in a different way.

For performance reason, the following change is desired:
* `tvm_model.predict(test_data)` works only for the same batch size TVM is compiled for. This means `tvm_model.predict(test_data)` is just a thin wrapper around TVM's `model.run()`. 
* For test data whose size is larger than the fixed batch size, introduce another API to return a list of prediction (as a list of ndarray), rather than a one big array. 

One possibility is to add `predict_batch(test_data)` API whose signature is ndarray -> [ndarray].
`predict(test_data)` works the same way as in current implementation, but a restriction needs to be added for TVM backend: the test data to be passed in needs to have the same batch size specified at compile time.

Let me know your thoughts @interesaaat @ksaur

**Comment by interesaaat** [comment]
I like this idea. Another problem with the current setup is that if the final prediction size is bigger than memory, we will fail. With this proposal we can solve also this issue as well as the performance problem. 

One minor point that I need to think about is the `predict_batch` API. I am not 100% sure that having a different signature will help here. I am a bit worried that we will add a technical detail (i.e., batching) to the main predict API will create confusion.
I would rather have a different `convert` signature accepting `batch_size` as parameter (basically something like `convert_batch` that overloads the current `convert` by adding a required `batch_size` parameter). The output of this new convert API will be a "batch" container where a call to predict will generate a list of predictions instead of just one prediction. WDYT?

**Comment by masahi** [comment]
I prefer following sklearn API convention, so that `predict(...)` always return an array. I imagine, returning a list of prediction is already confusing to users, so having a new, dedicated API (`predict_batch` or whatever) would be less surprising. 

So if users use this new API, we can assume that users know what they are doing. Returning a list of array, although awkward, should be no brainer in that case.

**Comment by interesaaat** [comment]
One problem I have with the different API is its usage wrt convert and the `batch_size` parameter. Like if in `convert` someone passes `batch_size` the expectation is that the prediction will do batching, but this won't happen if the user picks `predict` instead of `predict_batch`. Similarly, if no `batch_size` is passed at convert time, still a user could pick `predict_batch`, i.e., because they think HB could do batching automatically. 

Bottomline, I think that introducing 2 different ways of doing prediction plus how we set `batch_size` at conversion time could be confusing for users. I think that having a specific conversion API instead (`convert_batch`), and stick with a single prediction API (although returning 2 different types if used w\ or w\o batching) could be a little less confusing.

**Comment by masahi** [comment]
ok let's do `convert_batch` then. So if a user uses the plain `convert` with TVM backend, the compiled model can only `predict` on the dataset whose #of rows is the same as `test_input`. I think this is the majority of use cases and this is what we should advertise as the recommended usage. We never have to mention `batch_size` stuff in `convert` API, to keep it clean and simple. I like that.

Maybe we can discuss what the API of `convert_batch` should be. Actually I'm not sure when users would want to use `convert_batch`... By requiring `test_input` to be passed as an argument, we are assuming that users know the shape of target dataset. But if the target shape is fixed at convert time, why would anyone want to use `convert_batch` instead of `convert`? 

If the dataset size is known but doesn't fit in memory, then yes, `convert_batch` makes sense. But then, requiring `test_input` to be passed in is not a good idea, since it won't fit into memory (by assumption) and we only need `batch_size` portion of the `test_input` for tracing anyway.

So instead of asking
* `test_input` (which can be huge and won't fit to memory) 
* `batch_size` (10000, say) 

We can ask
* `trace_input`, whose # of rows we interpret as `batch_size`
* `test_input_rows` (a big number)

Thoughts?

**Comment by interesaaat** [comment]
At least we converged for one aspect :smiley:.

I think you have a good point regarding `test_input`. Right now we are passing the full dataset because (1) we need to compute the remainder (that's why `batch_size` alone won't help) and (2) we need to know the number of features. One possibility is to ask for `trace_input` to be `some_multiple_of_batch_size + remainder_size` and then have `batch_size` as second parameter. We don't really need to know the total size of the dataset at conversion time (for the `convert_batch` case), so I don't think we need `text_input_rows`.

**Comment by masahi** [comment]
Well if we assume that users can calculate `remainder_size`, then why not simply ask 
* `trace_input` (`batch_size` x num feature) array
* `remainder_size` (an int smaller than `batch_size`, maybe default to 0)

?

If `remainder_size` is > 0, we create `remainder_model`. From `trace_input` and `remainder_size`, we can create `remainder_trace_input`. 

This is the minimal and necessary info to enable prediction on `batch_size` * `k` + `remainder_size` test inputs.

**Comment by interesaaat** [comment]
You are right. Remainder will always be smaller than batch_size so that we can trace using the trace_input also over remainder. Yep.

**Comment by masahi** [comment]
Ok I'll work on the implementation next week.
