### ISSUE TITLE
Use hummingbird with synapseML

### ISSUE THREAD

**Issue by congnt-dsv** [microsoft/hummingbird#571]
Can we use hummingbird with synapseML model?

**Comment by congnt-dsv** [comment]
I want to convert this model, but current have problems.
![image](https://user-images.githubusercontent.com/43123781/158002273-81dde16d-c8ea-4776-b6a1-56e2c1086345.png)
![image](https://user-images.githubusercontent.com/43123781/158002282-70a52702-3a89-40fc-9d4f-fd31d508e18a.png)

**Comment by interesaaat** [comment]
Hi! I assume this is LightGBM from SynapseML, right? The trace is truncated but since it is going into `_convert_sparkml` I presume that is the case. So if this is true, we don't currently support the LightGBM implementation in SynapseML (although we support the original LightGBM library). I think it is possible to add the SynapseML LightGBM support into Hummingbird if you need it. Question: are you using a machine with GPU? Otherwise I am not sure Hummingbird will be able to accelerate this model on CPU.

**Comment by congnt-dsv** [comment]
Hi! Thank you for your quick response.
I'm using CPU and have to find method to speedup prediction step.
