### ISSUE TITLE
Hummingbird documentation document generation broken

### ISSUE THREAD

**Issue by cxie00** [microsoft/hummingbird#597]
https://microsoft.github.io/hummingbird/api/hummingbird.ml.supported.html among other links display blank pages. The documentation is missing.

**Comment by ksaur** [comment]
Thank you, you're right. We just had some pipeline changes, so it seems something is broken. We'll take a look.

**Comment by ksaur** [comment]
Update: the last PR where we deprecate `torch==1.7` causes the doc generation to fail.  

For some reason, the docs only generate with torch==1.5 (due to a conflict), so I pinned doc generation to the working eversion. But now that we mandate `torch>1.7`, it [errors out](https://github.com/microsoft/hummingbird/runs/6989934612?check_suite_focus=true) in the "Generate Documentation" phase (`AssertionError: Please install torch >1.7.0`). 

When we generate the docs with the newest torch we get

```
make sphinx-site -C website/
....
reading sources... [  3%] api/hummingbird.ml._executor                                                                                      
Extension error (sphinx.ext.linkcode):
Handler <function doctree_read at 0x7f67bd6ccee0> for event 'doctree-read' threw an exception (exception: type object 'Executor' has no attribute '_is_full_backward_hook')
```

**Comment by ksaur** [comment]
Ok the PR is in progress...for some reason I get a [segfault](https://github.com/microsoft/hummingbird/runs/7015107542?check_suite_focus=true) when building the doc (`free(): invalid pointer`).

It [worked](https://ksaur.github.io/hummingbirdtest/api/hummingbird.ml._topology.html) (meaning everything was successfully generated w/o issue) when I deployed it from my own account.
