### ISSUE TITLE
Question about Hummingbird performance on XGB-example.ipynb file.

### ISSUE THREAD

**Issue by zhangjian94cn** [microsoft/hummingbird#622]
I'm testing hummingbird performance in my computer which has **Intel Xeon CPU E5-2697 v2 @2.70Ghz with 48 cores**. 
In your OSDI 2020's paper, you used NC6 v2 machine machine equipped with **Intel Xeon CPU E5-2690 v4 @2.60Ghz (6 virtual cores)**. 

However, I found ours results were slower than yours. When testing XGB-example.ipynb file, I found that it consumed **700+ ms** to finish running Hummingbird on CPU. So what is the platform you use to test currently?

Another problem is that, when I testing xgboost in cpu (use original model to predict), I found that it were  **40+ times faster** than Hummingbird on CPU. It makes me confused.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/18614548/185555393-9c331263-2085-49a2-98ad-19afa4d6c9a6.png">

By the way, I use [.devcontainer](https://github.com/microsoft/hummingbird/tree/main/.devcontainer) to setup environment.

**Comment by ksaur** [comment]
Hi @zhangjian94cn !  Thanks for trying out Hummingbird. :)

Even though you used the same hardware, since these numbers are from early 2020, lots of new software has likely been released in the past 2.5 years, so I don't expect performance to be the same as in the paper even though you used the same underlying hardware.   For example, we found a performance regression with pytorch between v1.5 and 1.6 (I think those were the versions), but then a speedup in torch 1.7.  Since we can't control 3rd party libraries, it makes it a bit difficult to always get the expected performance, but we do our best!

We don't do much performance testing on CPU specifically, and lately have been using v100's to get the best performance.

Do you have a specific model that you'd like to see speed up on?  Or a specific use case in mind?

**Comment by interesaaat** [comment]
To add to what Karla says, we usually gets the best performance using the TVM backend. PyTorch does not parallelize all the kernels on CPU so it is not surprise that having more cores does not help much with the performance. TVM should be better in this respect.

**Comment by zhangjian94cn** [comment]
@interesaaat @ksaur Thanks for your response! I'm trying to evaluate several inference frameworks which can accelerate the speed of prediction, such as hummingbird, FIL and so on. Therefore, I want to set a reasonable environment to evaluate these methods fairly. 

Considering the version of current library (newest pytorch's version is 1.12), any suggestion could you provide to help me set the reasonable environment (hardware, software, lib version)?

**Comment by ksaur** [comment]
If you don't have a hard requirement on Pytorch, then TVM is the fastest backend. You can look at our pipeline for how to install it depending on your platform ([example](https://github.com/microsoft/hummingbird/blob/main/.github/workflows/pythonapp.yml#L80)).

The NC6 v3's are considerably faster than the NC6 v2, so that also is a useful option.  

Please let us know if you hit any issues or have more questions! :)

**Comment by zhangjian94cn** [comment]
@ksaur Thank you very much!
