### ISSUE TITLE
Remove not required dependencies

### ISSUE THREAD

**Issue by interesaaat** [microsoft/hummingbird#68]
Should we leave `sklearn`? From one site having `sklearn` will help first time users, but on the other side, everyone taking a dependency on `hummingbird` will have to install `sklearn` even if it is not used.

**Comment by interesaaat** [comment]
Maybe we can have something like [this](https://github.com/DLR-RM/stable-baselines3#install-using-pip) (having some optional param to the `pip install` if users want to install all dependencies).

**Comment by interesaaat** [comment]
We should put all "dev" dependencies into `requirements-dev.txt` while leaving `requirements.txt` with only the strictly necessary stuff.

**Comment by ksaur** [comment]
To  your  original question, I mostly think we should have sklearn,  because without at least one of  {sklearn/xgboost/lgbm} hummingbird will not function. But lgbm-only users may not want sklearn.  

Maybe sklearn is the "default" option, and then if the user explicitly specifies lgbm for example, it can override.
